# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f534e8720b12c275bf8e32460116dbd98dee786f6a4936abae90f2d1c89b7012ab02b3a53e22188f8621fea545c11eaa2dc48440ecc21ddbc7c59fa1b5ed6e1c

test:
  secret_key_base: eed0652557ef1bdfc2cd7d6c4108c36701f63204f3f51d22138ba99d14c997ab6683cedf0ad88f0b81eadf9aa3013d4d33679487768ca7a865034aeff5ec9ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
